### ISSUE TITLE
ZNS Connect on Zora 

### ISSUE THREAD

**Issue by bond-zns** [ourzora/ocs-hackathon-24#8]
We are ZNS Family. We are building EVM name service.
Today already 620.000 domains minted on Berachain and 40.000 on Scroll. 

We offer custom domain creation for your community with the domain extension .zora on the Zora chain. 

Here are the details:

1. Integration typically takes 3 days.
2. You no need to cover gas fees and small backend services. 
3. We propose revenue sharing 
4. We will create custom domain name [zora.znsconnect.io](https://yourname.znsconnect.io/) ( like we made for OKX team https://okx.znsconnect.io/) 

Thank you 🙏

Please join chat :  https://https://t.me/+XK8SHZzgQqtiYjdi

**Comment by iainnash** [comment]
This is not the right forum for this and will close out.
